name: flutter_aws_s3_client
description: A simple, unofficial AWS S3 client in dart. Supports downloading objects and listing objects in a bucket.
version: 0.5.0
author: Diagnosia <support@diagnosia.com>
homepage: https://github.com/diagnosia/flutter_aws_s3_client
environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  amazon_cognito_identity_dart: ^0.0.22
  built_value: '>=6.8.0 <8.0.0'
  built_collection: '>=4.0.0 <5.0.0'
  xml2json: ^4.1.0
  http: ^0.12.0+2
dev_dependencies:
  test: ^1.0.0
  built_value_generator: '>=6.8.0 <8.0.0'
  build_runner: ^1.7.1
  json_serializable: '>=3.2.2 <4.0.0'
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  #assets:
  #  - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
